//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB6Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_id { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Message_Data { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public string Various { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
