//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CB6Project
{
    using System;
    
    public enum RoleType : int
    {
        Admin = 1,
        SuperMOD = 2,
        MOD = 3,
        CustomUser = 4
    }
}
